import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import { Providers } from "@/components/providers";

import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RoomRoam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="min-h-screen bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]">
          <NavBar />
          {children}
          <Footer/>
          <Toaster position="top-center" />
          </div>
        </Providers>
      </body>
    </html>
  );
}
{/* <div class="absolute top-0 z-[-2] h-screen w-screen "></div> */}