import { Providers } from "@/components/providers";

import React from "react";

import "../globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-dark-1`}>
        <Providers>
          <div className="min-h-screen">
            {children}
            <Toaster position="top-center" />
          </div>
        </Providers>
      </body>
    </html>
  );
}
